'use client';
import Link from 'next/link';
import { useStore } from '@/lib/store-context';
import { DEFAULT_COMMERCE_SETTINGS } from '@repo/types';
import { POLICY_TITLES } from '@/lib/policies';
export function Footer() {
  const { store, categories } = useStore();
  if (!store) return null;
  const settings = { ...DEFAULT_COMMERCE_SETTINGS, ...store.commerce };
  return <footer className="bg-[#142523] px-5 pb-8 pt-14 text-white md:px-8"><div className="mx-auto max-w-7xl"><div className="grid gap-10 sm:grid-cols-2 lg:grid-cols-4"><div><Link href="/" className="text-2xl font-bold tracking-tight">crabtile.</Link><p className="mt-4 text-sm leading-6 text-white/60">{settings.businessAddress}</p><a className="mt-4 block text-sm underline underline-offset-4" href={`mailto:${settings.supportEmail}`}>{settings.supportEmail}</a>{settings.supportPhone && <a href={`tel:${settings.supportPhone}`} className="mt-2 block text-sm">{settings.supportPhone}</a>}</div><div><h2 className="mb-5 text-sm font-semibold">Explore</h2><ul className="space-y-3 text-sm text-white/60"><li><Link href={`/${store.slug}/products`}>All products</Link></li>{categories.filter(c=>!c.parentId).map(c=><li key={c._id}><Link href={`/${store.slug}/category/${c.slug}`}>{c.name}</Link></li>)}<li><Link href="/">All collections</Link></li></ul></div><div><h2 className="mb-5 text-sm font-semibold">Customer care</h2><ul className="space-y-3 text-sm text-white/60"><li><Link href={`/${store.slug}/account/orders`}>Track your order</Link></li><li><Link href={`/${store.slug}/account`}>Your account</Link></li>{Object.entries(POLICY_TITLES).filter(([key])=>['contact','shipping-policy','returns-refunds'].includes(key)).map(([key,title])=><li key={key}><Link href={`/${store.slug}/${key}`}>{title}</Link></li>)}</ul></div><div><h2 className="mb-5 text-sm font-semibold">About Crabtile</h2><ul className="space-y-3 text-sm text-white/60">{Object.entries(POLICY_TITLES).filter(([key])=>['about-us','privacy-policy','terms-and-conditions'].includes(key)).map(([key,title])=><li key={key}><Link href={`/${store.slug}/${key}`}>{title}</Link></li>)}</ul></div></div><div className="mt-12 flex flex-wrap justify-between gap-4 border-t border-white/15 pt-6 text-xs text-white/50"><span>© {new Date().getFullYear()} {settings.businessName}. All rights reserved.</span><span>India · INR (₹)</span></div></div></footer>;
}
