substitutions:
  _REGION: asia-south1
  _REPOSITORY: cloud-run-source-deploy
  _SERVICE: crabtile-shop-backend
  _TAG: manual

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - Dockerfile.backend
      - --tag
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:${_TAG}
      - .

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:${_TAG}
