import { pgTable, text, doublePrecision, numeric, boolean, timestamp, jsonb, index, uniqueIndex, check } from 'drizzle-orm/pg-core';
import type { AnyPgColumn } from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';

// Scalar fields are SQL columns; nested value objects and ordered lists use JSONB.
// Keep the public 24-character IDs so existing clients retain their API contract.
export const BillboardTable = pgTable('billboard', {
  storeId: text('storeId').notNull().references(() => StoreTable._id),
  categoryId: text('categoryId'),
  title: text('title').notNull(),
  subtitle: text('subtitle'),
  imageUrl: text('imageUrl').notNull(),
  ctaText: text('ctaText'),
  ctaLink: text('ctaLink'),
  order: doublePrecision('order').default(0),
  isActive: boolean('isActive').default(true),
  _id: text('_id').primaryKey(),
  createdAt: timestamp('createdAt', { precision: 3, withTimezone: true, mode: 'date' }).notNull().defaultNow(),
  updatedAt: timestamp('updatedAt', { precision: 3, withTimezone: true, mode: 'date' }).notNull().defaultNow(),
}, (t) => [
  index('billboard_idx_0').on(t.storeId),
  index('billboard_idx_1').on(t.categoryId),
  index('billboard_idx_2').on(t.order),
  index('billboard_idx_3').on(t.isActive),
  index('billboard_idx_4').on(t.storeId, t.order),
]);

export const CategoryTable = pgTable('category', {
  storeId: text('storeId').notNull().references(() => StoreTable._id),
  name: text('name').notNull(),
  slug: text('slug').notNull(),
  description: text('description'),
  imageUrl: text('imageUrl'),
  parentId: text('parentId').references((): AnyPgColumn => CategoryTable._id),
  isFeatured: boolean('isFeatured').default(false),
  order: doublePrecision('order').default(0),
  isActive: boolean('isActive').default(true),
  billboards: jsonb('billboards').default([]),
  _id: text('_id').primaryKey(),
  createdAt: timestamp('createdAt', { precision: 3, withTimezone: true, mode: 'date' }).notNull().defaultNow(),
  updatedAt: timestamp('updatedAt', { precision: 3, withTimezone: true, mode: 'date' }).notNull().defaultNow(),
}, (t) => [
  index('category_idx_0').on(t.storeId),
  index('category_idx_1').on(t.slug),
  index('category_idx_2').on(t.parentId),
  index('category_idx_3').on(t.isFeatured),
  index('category_idx_4').on(t.order),
  index('category_idx_5').on(t.isActive),
  uniqueIndex('category_idx_6').on(t.storeId, t.slug),
]);

export const NewsletterSubscriberTable = pgTable('newsletter_subscriber', {
  storeId: text('storeId').notNull().references(() => StoreTable._id),
  email: text('email').notNull(),
  status: text('status').default("subscribed"),
  consentAt: timestamp('consentAt', { precision: 3, withTimezone: true, mode: 'date' }).notNull().defaultNow(),
  source: text('source').default("storefront_home"),
  _id: text('_id').primaryKey(),
  createdAt: timestamp('createdAt', { precision: 3, withTimezone: true, mode: 'date' }).notNull().defaultNow(),
  updatedAt: timestamp('updatedAt', { precision: 3, withTimezone: true, mode: 'date' }).notNull().defaultNow(),
}, (t) => [
  index('newsletter_subscriber_idx_0').on(t.storeId),
  uniqueIndex('newsletter_subscriber_idx_1').on(t.storeId, t.email),
  check('newsletter_subscriber_status_enum', sql`${t.status} in ('subscribed', 'unsubscribed')`),
]);

export const OrderTable = pgTable('order', {
  checkoutKey: text('checkoutKey'),
  checkoutFingerprint: text('checkoutFingerprint'),
  paymentCreationStartedAt: timestamp('paymentCreationStartedAt', { precision: 3, withTimezone: true, mode: 'date' }),
  inventoryStatus: text('inventoryStatus').default("uncommitted"),
  storeId: text('storeId').notNull().references(() => StoreTable._id),
  orderNumber: text('orderNumber').notNull(),
  customer: jsonb('customer'),
  items: jsonb('items').default([]),
  subtotal: numeric('subtotal', { precision: 12, scale: 2, mode: 'number' }).notNull(),
  tax: numeric('tax', { precision: 12, scale: 2, mode: 'number' }).default(0),
  shipping: numeric('shipping', { precision: 12, scale: 2, mode: 'number' }).default(0),
  discount: numeric('discount', { precision: 12, scale: 2, mode: 'number' }).default(0),
  total: numeric('total', { precision: 12, scale: 2, mode: 'number' }).notNull(),
  status: text('status').default("pending"),
  paymentStatus: text('paymentStatus').default("pending"),
  paymentMethod: text('paymentMethod'),
  transactionId: text('transactionId'),
  razorpayOrderId: text('razorpayOrderId'),
  shippingAddress: jsonb('shippingAddress'),
  billingAddress: jsonb('billingAddress'),
  fulfillment: jsonb('fulfillment'),
  statusHistory: jsonb('statusHistory').default([]),
  notes: text('notes'),
  _id: text('_id').primaryKey(),
  createdAt: timestamp('createdAt', { precision: 3, withTimezone: true, mode: 'date' }).notNull().defaultNow(),
  updatedAt: timestamp('updatedAt', { precision: 3, withTimezone: true, mode: 'date' }).notNull().defaultNow(),
}, (t) => [
  uniqueIndex('order_idx_0').on(t.checkoutKey),
  index('order_idx_1').on(t.storeId),
  uniqueIndex('order_idx_2').on(t.orderNumber),
  index('order_idx_3').on(t.status),
  index('order_idx_4').on(t.paymentStatus),
  index('order_idx_5').on(t.transactionId),
  index('order_idx_6').on(t.razorpayOrderId),
  index('order_customer_email_idx').on(sql`lower(${t.customer}->>'email')`),
  index('order_customer_user_idx').on(sql`(${t.customer}->>'userId')`),
  index('order_store_created_idx').on(t.storeId, t.createdAt),
  check('order_inventoryStatus_enum', sql`${t.inventoryStatus} in ('uncommitted', 'committed', 'released', 'review')`),
  check('order_status_enum', sql`${t.status} in ('pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled', 'refunded')`),
  check('order_paymentStatus_enum', sql`${t.paymentStatus} in ('pending', 'paid', 'failed', 'refunded')`),
]);

export const OtpTable = pgTable('otp', {
  attempts: doublePrecision('attempts').default(0),
  email: text('email').notNull(),
  otp: text('otp').notNull(),
  type: text('type').default("login"),
  expiresAt: timestamp('expiresAt', { precision: 3, withTimezone: true, mode: 'date' }).notNull(),
  _id: text('_id').primaryKey(),
  createdAt: timestamp('createdAt', { precision: 3, withTimezone: true, mode: 'date' }).notNull().defaultNow(),
  updatedAt: timestamp('updatedAt', { precision: 3, withTimezone: true, mode: 'date' }).notNull().defaultNow(),
}, (t) => [
  index('otp_idx_0').on(t.email),
  index('otp_idx_1').on(t.expiresAt),
  uniqueIndex('otp_idx_2').on(t.email, t.type),
  check('otp_type_enum', sql`${t.type} in ('login', 'register', 'order_confirmation')`),
]);

export const PageTable = pgTable('page', {
  storeId: text('storeId').notNull().references(() => StoreTable._id),
  title: text('title').notNull(),
  slug: text('slug').notNull(),
  description: text('description'),
  metaTitle: text('metaTitle'),
  metaDescription: text('metaDescription'),
  isPublished: boolean('isPublished').default(false),
  isHomePage: boolean('isHomePage').default(false),
  sections: jsonb('sections').default([]),
  _id: text('_id').primaryKey(),
  createdAt: timestamp('createdAt', { precision: 3, withTimezone: true, mode: 'date' }).notNull().defaultNow(),
  updatedAt: timestamp('updatedAt', { precision: 3, withTimezone: true, mode: 'date' }).notNull().defaultNow(),
}, (t) => [
  index('page_idx_0').on(t.storeId),
  index('page_idx_1').on(t.isPublished),
  index('page_idx_2').on(t.isHomePage),
  uniqueIndex('page_idx_3').on(t.storeId, t.slug),
  index('page_idx_4').on(t.storeId, t.isHomePage),
  uniqueIndex('page_one_home_per_store').on(t.storeId).where(sql`${t.isHomePage} = true`),
]);

export const ProductTable = pgTable('product', {
  storeId: text('storeId').notNull().references(() => StoreTable._id),
  name: text('name').notNull(),
  slug: text('slug').notNull(),
  description: text('description').default(""),
  featuredImage: text('featuredImage').notNull(),
  mediaGallery: jsonb('mediaGallery').default([]),
  mrp: numeric('mrp', { precision: 12, scale: 2, mode: 'number' }).notNull(),
  sellingPrice: numeric('sellingPrice', { precision: 12, scale: 2, mode: 'number' }).notNull(),
  categoryId: text('categoryId').notNull().references((): AnyPgColumn => CategoryTable._id),
  attributes: jsonb('attributes').default([]),
  isFeatured: boolean('isFeatured').default(false),
  sku: text('sku'),
  isActive: boolean('isActive').default(true),
  stock: doublePrecision('stock').notNull().default(0),
  hasVariants: boolean('hasVariants').default(false),
  variantOptions: jsonb('variantOptions').default([]),
  _id: text('_id').primaryKey(),
  createdAt: timestamp('createdAt', { precision: 3, withTimezone: true, mode: 'date' }).notNull().defaultNow(),
  updatedAt: timestamp('updatedAt', { precision: 3, withTimezone: true, mode: 'date' }).notNull().defaultNow(),
}, (t) => [
  index('product_idx_0').on(t.storeId),
  index('product_idx_1').on(t.slug),
  index('product_idx_2').on(t.categoryId),
  index('product_idx_3').on(t.isFeatured),
  index('product_idx_4').on(t.isActive),
  uniqueIndex('product_idx_5').on(t.storeId, t.slug),
  check('product_stock_nonnegative', sql`${t.stock} >= 0`),
  index('product_catalog_idx').on(t.storeId, t.isActive, t.categoryId, t.createdAt),
  index('product_search_idx').using('gin', sql`to_tsvector('simple', coalesce(${t.name}, '') || ' ' || coalesce(${t.description}, ''))`),
  check('product_mrp_nonnegative', sql`${t.mrp} >= 0`),
  check('product_sellingPrice_nonnegative', sql`${t.sellingPrice} >= 0`),
]);

export const StoreTable = pgTable('store', {
  name: text('name').notNull(),
  slug: text('slug').notNull(),
  domain: text('domain'),
  description: text('description'),
  logo: text('logo'),
  owner: text('owner'),
  commerce: jsonb('commerce'),
  seo: jsonb('seo'),
  theme: jsonb('theme'),
  navigation: jsonb('navigation').default([]),
  footer: jsonb('footer'),
  topBar: jsonb('topBar'),
  isActive: boolean('isActive').default(true),
  homeBillboards: jsonb('homeBillboards').default([]),
  homeSections: jsonb('homeSections').default([]),
  _id: text('_id').primaryKey(),
  createdAt: timestamp('createdAt', { precision: 3, withTimezone: true, mode: 'date' }).notNull().defaultNow(),
  updatedAt: timestamp('updatedAt', { precision: 3, withTimezone: true, mode: 'date' }).notNull().defaultNow(),
}, (t) => [
  uniqueIndex('store_idx_0').on(t.slug),
  index('store_idx_1').on(t.domain),
  index('store_idx_2').on(t.owner),
  index('store_idx_3').on(t.isActive),
]);

export const TransactionTable = pgTable('transaction', {
  refundError: text('refundError'),
  refundPending: boolean('refundPending').default(false),
  refundId: text('refundId'),
  orderId: text('orderId').notNull().references(() => OrderTable._id),
  storeId: text('storeId').notNull().references(() => StoreTable._id),
  razorpayOrderId: text('razorpayOrderId').notNull(),
  razorpayPaymentId: text('razorpayPaymentId'),
  razorpaySignature: text('razorpaySignature'),
  amount: numeric('amount', { precision: 12, scale: 2, mode: 'number' }).notNull(),
  currency: text('currency').notNull().default("INR"),
  status: text('status').default("created"),
  method: text('method'),
  email: text('email'),
  phone: text('phone'),
  notes: jsonb('notes'),
  errorCode: text('errorCode'),
  errorDescription: text('errorDescription'),
  _id: text('_id').primaryKey(),
  createdAt: timestamp('createdAt', { precision: 3, withTimezone: true, mode: 'date' }).notNull().defaultNow(),
  updatedAt: timestamp('updatedAt', { precision: 3, withTimezone: true, mode: 'date' }).notNull().defaultNow(),
}, (t) => [
  index('transaction_idx_0').on(t.orderId),
  index('transaction_idx_1').on(t.storeId),
  uniqueIndex('transaction_idx_2').on(t.razorpayOrderId),
  index('transaction_idx_3').on(t.razorpayPaymentId),
  index('transaction_idx_4').on(t.status),
  check('transaction_status_enum', sql`${t.status} in ('created', 'authorized', 'captured', 'failed', 'refunded')`),
  check('transaction_amount_nonnegative', sql`${t.amount} >= 0`),
]);

export const UserTable = pgTable('user', {
  email: text('email').notNull(),
  emailVerified: boolean('emailVerified').default(false),
  password: text('password').notNull(),
  name: text('name').notNull(),
  role: text('role').default("customer"),
  addresses: jsonb('addresses').default([]),
  _id: text('_id').primaryKey(),
  createdAt: timestamp('createdAt', { precision: 3, withTimezone: true, mode: 'date' }).notNull().defaultNow(),
  updatedAt: timestamp('updatedAt', { precision: 3, withTimezone: true, mode: 'date' }).notNull().defaultNow(),
}, (t) => [
  uniqueIndex('user_idx_0').on(t.email),
  check('user_role_enum', sql`${t.role} in ('customer', 'admin', 'store_owner')`),
]);

export const ProductVariantTable = pgTable('product_variant', {
  productId: text('productId').notNull().references(() => ProductTable._id),
  name: text('name').notNull(),
  sku: text('sku').notNull(),
  price: numeric('price', { precision: 12, scale: 2, mode: 'number' }).notNull(),
  compareAtPrice: numeric('compareAtPrice', { precision: 12, scale: 2, mode: 'number' }).default(0),
  stock: doublePrecision('stock').notNull().default(0),
  images: jsonb('images').default([]),
  featuredImageIndex: doublePrecision('featuredImageIndex').default(0),
  attributes: jsonb('attributes').notNull(),
  isActive: boolean('isActive').default(true),
  _id: text('_id').primaryKey(),
  createdAt: timestamp('createdAt', { precision: 3, withTimezone: true, mode: 'date' }).notNull().defaultNow(),
  updatedAt: timestamp('updatedAt', { precision: 3, withTimezone: true, mode: 'date' }).notNull().defaultNow(),
}, (t) => [
  index('product_variant_idx_0').on(t.productId),
  uniqueIndex('product_variant_idx_1').on(t.sku),
  index('product_variant_idx_2').on(t.productId, t.attributes),
  check('product_variant_stock_nonnegative', sql`${t.stock} >= 0`),
  check('product_variant_price_nonnegative', sql`${t.price} >= 0`),
]);

// Shipping operations are persisted before external calls. Ambiguous results
// require reconciliation rather than repeating a potentially billable request.
export const ShipmentTable = pgTable('shipment', {
  orderId: text('order_id').primaryKey().references(() => OrderTable._id),
  providerOrderId: text('provider_order_id').unique(),
  providerShipmentId: text('provider_shipment_id').unique(),
  state: text('state').notNull().default('creating'),
  operation: text('operation'),
  parcel: jsonb('parcel').notNull(),
  awb: text('awb').unique(),
  courier: text('courier'),
  labelUrl: text('label_url'),
  pickupScheduled: boolean('pickup_scheduled').notNull().default(false),
  lastEventAt: timestamp('last_event_at', { precision: 3, withTimezone: true }),
  lastStatus: text('last_status'),
  createdAt: timestamp('created_at', { precision: 3, withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { precision: 3, withTimezone: true }).notNull().defaultNow(),
});
